name: go_test

# on:
#   pull_request:
#     types:
#       - opened
#       - synchronize
#       - reopened
#       - labeled
# obs:
#   test:
#     name: Test
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         go-version: 1.18.0

#     steps:
#       - name: Set up Go ${{ matrix.go-version }}
#         uses: actions/setup-go@v3
#         with:
#           go-version: ${{ matrix.go-version }}

#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Test
#         run: go test ./...

#       - name: Vet
#         run: go vet ./...
